// Automatically generated file. DO NOT EDIT.
// Generated by gen-device-svd.py from gba_arm7tdmi.svd, see <unknown>

// +build gba,gba

// Gameboy CPU (Sharp LR35902)
//

package gba

import (
	"runtime/volatile"
	"unsafe"
)

// Some information about this device.
const (
	DEVICE = "GBA"
)

// Interrupt numbers
const (
	IRQ_VBLANK = 0 // GBA Screen VRAM // Interrupt Subsystem
	IRQ_max    = 0 // Highest interrupt number on this device.
)

// Peripherals.
var (
	VRAM       = (*SCREEN_Type)(unsafe.Pointer(uintptr(0x6000000))) // GBA Screen VRAM
	Interrupts = (*INT_Type)(unsafe.Pointer(uintptr(0x200)))        // Interrupt Subsystem
)

// GBA Screen VRAM
type SCREEN_Type struct {
}

// Interrupt Subsystem
type INT_Type struct {
	InterruptEnable volatile.Register16
	_padding0       [3]volatile.Register16
	InterruptMaster volatile.Register16
}

// Bitfields for VRAM: GBA Screen VRAM
const ()

// Bitfields for Interrupts: Interrupt Subsystem
const (
	// InterruptEnable: 200h - IE - Interrupt Enable Register (R/W)
	INT_InterruptEnable_VBlank_Pos       = 0x0    // Position of VBlank field.
	INT_InterruptEnable_VBlank_Msk       = 0x1    // Bit mask of VBlank field.
	INT_InterruptEnable_VBlank           = 0x1    // Bit VBlank.
	INT_InterruptEnable_VBlank_Disabled  = 0x0    // Interrupt is not requested
	INT_InterruptEnable_VBlank_Requested = 0x1    // Interrupt delivery is requested
	INT_InterruptEnable_KeyPad_Pos       = 0xc    // Position of KeyPad field.
	INT_InterruptEnable_KeyPad_Msk       = 0x1000 // Bit mask of KeyPad field.
	INT_InterruptEnable_KeyPad           = 0x1000 // Bit KeyPad.
	INT_InterruptEnable_KeyPad_Disabled  = 0x0    // Interrupt is not requested
	INT_InterruptEnable_KeyPad_Requested = 0x1    // Interrupt delivery is requested

	// InterruptMaster: 208h - IME - Interrupt Master Enable Register (R/W)
	INT_InterruptMaster_Enable_Pos      = 0x0 // Position of Enable field.
	INT_InterruptMaster_Enable_Msk      = 0x1 // Bit mask of Enable field.
	INT_InterruptMaster_Enable          = 0x1 // Bit Enable.
	INT_InterruptMaster_Enable_Disabled = 0x0 // Interrupts are disabled (default)
	INT_InterruptMaster_Enable_Enabled  = 0x1 // Interrupts controlled by InterruptEnable
)
